### ISSUE TITLE
Govee devices not responding in HA. Unable to re-add integration.

### ISSUE THREAD

**Issue by rabacen** [LaggAt/hacs-govee#120]
Govee devices not responding in HA.

Removed integration, attempted to re-add integration, getting:
Cannot connect. Is the API-Key correct and the internet connection working?

Applied for new API key still not working.

Home Assistant 2023.7.2
Govee Integration 0.2.2

Govee android app can control devices.

Logs state rate exceeded however this can't be possible as the integration isn't working.

Logs when attempting to enter API key.
2023-08-02 08:06:55.906 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2023-08-02 08:06:55.907 ERROR (MainThread) [custom_components.govee.config_flow] Cannot connect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 68, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/config_flow.py", line 34, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

**Comment by rabacen** [comment]
Seems fine now, possibly Govee servers had a wobble this morning.
