### ISSUE TITLE
Unavailable

### ISSUE THREAD

**Issue by TobiasFriberg** [LaggAt/hacs-govee#122]
Unable to get Govee online, state won't change from "Failed to set up". I've used Govee for some time now but now it seems to be somewhat broken. I've changed the poll to 40 instead of default 10, still same issue. Not sure what's up.

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

```

**Comment by daniellammert** [comment]
SAME, SAME. I actually just installed home Assistant and have been playing around with it this last weekend for the first time. I was excited to see that they had goby support but sometime Sunday evening it went down the same way yours did. I hope we find a resolution quick!

**Comment by redneckzking** [comment]
Same...and I have been using the Govee for a while.  Something has changed and broke this integration.

**Comment by fernandor1sv** [comment]
Same here, I installed the integration yesterday and today is already broken

**Comment by cannondale0815** [comment]
You guys can try the other Govee integration [here](https://github.com/wez/govee-lan-hass) -- it still works ok with my H6199 TV Backlight.

**Comment by norimicry** [comment]
+1 unavailable devices with this integration

**Comment by bam27beer** [comment]
+1 just set up a 2 nd set of floods , nothing connect in the intergration when i reload
