### ISSUE TITLE
Unknown error when entering API key

### ISSUE THREAD

**Issue by treyes133** [LaggAt/hacs-govee#15]
I have looked through other issues. I saw that if you didn't have any devices, this error popped up, but I have added a device and can control it with my phone.

## Version of the custom_component
Using current beta version (0.1.6-beta.1)

## Configuration

Haven't configured, can't get through API key entry

Add your logs here.

Logger: custom_components.govee.config_flow
Source: custom_components/govee/config_flow.py:28
Integration: Govee LED strips (documentation, issues)
First occurred: 12:17:16 AM (3 occurrences)
Last logged: 12:19:52 AM

Unexpected exception: generator didn't stop after athrow()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 169, in _api_request_internal
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 152, in _api_get
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 356, in get_devices
    for item in result["data"]["devices"]:
KeyError: 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 48, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
  File "/config/custom_components/govee/config_flow.py", line 28, in validate_api_key
    _, error = await hub.get_devices()
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 410, in get_devices
    err = f"API-Error {response.status}: {result}"
  File "/usr/local/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 152, in _api_get
    yield response
  File "/usr/local/lib/python3.8/contextlib.py", line 190, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow()

Unable to enter the API key. Tried uninstalling a reinstalling two times. Rebooted server 3 times. Installed through HACS.

**Comment by treyes133** [comment]
Device might not be supported! Will try with a new device.
