### ISSUE TITLE
Error `has no attribute 'rate_limit_delay'`

### ISSUE THREAD

**Issue by wwelles** [LaggAt/hacs-govee#150]
## Configuration

```yaml


```

## Describe the bug
Integration stopped working after working for months

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:04:29 AM (2 occurrences)
Last logged: 10:13:58 AM

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'


```

**Comment by wwelles** [comment]
Sorry my bad here. I remembered I requested an API key for another integration. I used that key and everything worked. Clearly you can only have one key.
