### ISSUE TITLE
Constant "Cannot connect. Is the API-Key correct?"

### ISSUE THREAD

**Issue by gobbless88** [LaggAt/hacs-govee#153]
I understand I need to paste logs and configs- I simply can't get past the basic setup after I did a fresh HAos install. 

My new Govee API key worked in the Govee2Mqtt addon, yet I simply liked the HACS Govee add-on much better so I would like to pursue this further and get it back working.

It's giving me the message "Cannot connect. Is the API-Key correct and the internet connection working?"

I saw others had this issue quite frequently in last October.

**Comment by gobbless88** [comment]
only Log I see as relevant

Traceback (most recent call last):

  File "/config/custom_components/govee/config_flow.py", line 66, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/config_flow.py", line 32, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

**Comment by kalel681** [comment]
This! Having the same issue after changing Govee app password and getting new API key.

**Comment by gobbless88** [comment]
@LaggAt Have you confirmed this as a plugin bug or?

**Comment by magnetic157** [comment]
I'm having the same issues... my smart plugs suddenly stopped working and the integration suddenly started to fail on load.  I removed it and re-added it with a new API key and i'm getting the same error that it can't connect.

**Comment by gurufordy** [comment]
I was having the same issues and have since fixed the problem by moving to [Govee2MQTT ](https://github.com/wez/govee2mqtt)

**Comment by weesteev** [comment]
Confirmed, having this as well. Recently reinstalled HA OS and having the same issue with the Govee add on. Applied for a new API key and still getting the same error.

**Comment by John19711** [comment]
Same issue. Deleted the integration and got a new API but still have the issue.

**Comment by nickmajor329** [comment]
Same Problem

**Comment by designswagger** [comment]
Has anyone figured out a fix for this? I'm having the same issue. It worked, then stopped working and now it won't reconnect.

**Comment by aceonemg** [comment]
Same here. So frustrating

**Comment by popltree2** [comment]
> Same here. So frustrating
Last line in the log shows it's a rate limit issue. I suggest reducing your polling.

**Comment by YoanKECH** [comment]
Mine wasnt working since few weeks, uninstaled it ands reinstalled, now got the same issue as here
