### ISSUE TITLE
Can't Connect to API

### ISSUE THREAD

**Issue by RichardKeschinger** [LaggAt/hacs-govee#160]
I am seeing this on different threads/issues but i haven't found a viable solution yet. 

i get this everytime i try to change the current API. is the only solution to wait?

"Cannot connect. Is the API-Key correct and the internet connection working?"

**Comment by CrasyHarry** [comment]
same problem here... :-(
cant set up the integration...

"Cannot connect. Is the API-Key correct and the internet connection working?"

**Comment by RichardKeschinger** [comment]
> same problem here... :-(
> 
> cant set up the integration...
> 
> 
> 
> "Cannot connect. Is the API-Key correct and the internet connection working?"
> 
> 
> 
> 

I had to use different integration

**Comment by CrasyHarry** [comment]
today it works. 
I don't know why it didn't work yesterday, but I waited 24 hours and now I was able to set up the integration..

**Comment by RichardKeschinger** [comment]
Yea it's gonna happen everytime you hit that poll limit or whatever

**Comment by funnymataleao** [comment]
Same issue here. How to fix it?

**Comment by RichardKeschinger** [comment]
> Same issue here. How to fix it?

Govee to MQTT

**Comment by alanrenouf** [comment]
Same issue here

**Comment by alanrenouf** [comment]
> > Same issue here. How to fix it?
> 
> Govee to MQTT

Got a good guide?

**Comment by RichardKeschinger** [comment]
> > > Same issue here. How to fix it?
> 
> > 
> 
> > Govee to MQTT
> 
> 
> 
> Got a good guide?

YouTube will help you well

**Comment by dc7707** [comment]
FWIW: I am getting:

 Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 66, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/config_flow.py", line 32, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

The funny thing here is I can fire up a quick python script and make api calls successfully without getting any limit reach or errors at all. Could there be a bug in the validation?

**Comment by nekrosoft13** [comment]
> > > > Same issue here. How to fix it?
> > 
> > 
> > > 
> > 
> > 
> > > Govee to MQTT
> > 
> > 
> > Got a good guide?
> 
> YouTube will help you well

any actual guides to follow? instead of youtube?

**Comment by rhino53150** [comment]
> > > > > Same issue here. How to fix it?
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Govee to MQTT
> > > 
> > > 
> > > Got a good guide?
> > 
> > 
> > YouTube will help you well
> 
> any actual guides to follow? instead of youtube?

Govee to MQTT is broke also. Will only work if you have Local API available on your devices. The IOT mode doesn't work.

**Comment by emn83** [comment]
Today it suddenly doesn't connect, changed API and neither, uninstalled and installed again and nothing

**Comment by ktiedt** [comment]
Same problem here, have updated everything and reinstalled the Govee integration to no avail

**Comment by Noack1978** [comment]
I have the same problem. A new api-key is not accepted

**Comment by 1975felix** [comment]
I have same problem. Request new api but not accepted

**Comment by Blankf** [comment]
same here, getting 500s now, and new api-key is not accepted
