### ISSUE TITLE
Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset

### ISSUE THREAD

**Issue by ThierryBegin** [LaggAt/hacs-govee#164]
## Version of the custom_component

22023.11.1
## Configuration

```
No YAML, using the Integration path.

```

## Describe the bug
Rate Limits are exceeding, the integration fail to connect.

## Debug log

```
2024-05-24 09:46:46.993 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
2024-05-24 09:46:58.976 WARNING (MainThread) [custom_components.govee] API is back online.
2024-05-24 09:46:58.977 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2024-05-24 09:46:58.977 WARNING (MainThread) [custom_components.govee] Could not connect to Govee API: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2024-05-24 09:46:58.978 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?

```

**Comment by Dapounet** [comment]
@sam-eureka : be careful, the poll interval set depends on how many Govee devices you have on your network.
While 60 can be the right value, it can be something else for somebody else.

1 request per minute (60 seconds) = 60 requests per hour = 1440 requests/day.
You can have up to 7 devices with this value (7 devices * 1440 requests/day = 9800 requests/day, below the 10 000 limit).

**Comment by Hanselljlh** [comment]
Is there a way to see when it is polling? Or what is polling? I have 4 devices and apparently hitting the limit. I have one mobile device that I use to setup everything that eventually links into HA... Unless I am setting up or fixing something the mobile device is off.
