### ISSUE TITLE
Govee integration breaks Roborock integration

### ISSUE THREAD

**Issue by r77s** [LaggAt/hacs-govee#169]
## Version of the custom_component: 
Wenn I install this integration with version 2023.11.1 and reboot my HA, this integration breaks the build in HA integration from roborock.

``Logger: homeassistant.setup
Quelle: setup.py:320
Erstmals aufgetreten: 09:46:44 (1 Vorkommnisse)
Zuletzt protokolliert: 09:46:44

Setup failed for custom integration 'roborock': Unable to import component: No module named 'imp'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
component = await integration.async_get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
self._component_future.result()
File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
comp = await self.hass.async_add_import_executor_job(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/init.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "", line 1387, in _gcd_import
File "", line 1360, in _find_and_load
File "", line 1331, in _find_and_load_unlocked
File "", line 935, in _load_unlocked
File "", line 995, in exec_module
File "", line 488, in _call_with_frames_removed
File "/config/custom_components/roborock/init.py", line 10, in
from roborock.api import RoborockApiClient
File "/usr/local/lib/python3.12/site-packages/roborock/api.py", line 60, in
from .protocol import Utils
File "/usr/local/lib/python3.12/site-packages/roborock/protocol.py", line 12, in
from construct import ( # type: ignore
File "/usr/local/lib/python3.12/site-packages/construct/init.py", line 22, in
from construct.core import *
File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in
import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'``

## Debug log

```text

Add your logs here.

```

**Comment by JStaegerino** [comment]
Same issue here

**Comment by simongis** [comment]
Same issue here, updating to 2024.7.0 now

**Comment by r77s** [comment]
I am not sure what happends. After a few time uninstall the govee integration and the roborock integration and some reboots I can use both without any issue. Maybe the new HA version fixed it. I don't know what happends.

**Comment by evergreen0057** [comment]
I am also encountering this issue. Everytime I have to restart HA I have to disable the Govee integration first > Restart HA > Wait for everything to load > Then enable Govee integration again afterwards and everything seems to works ok but this is a bit inconvenient and I often forget to disable it before a restart.

Is there any plan for a fix for this issue?

**Comment by SebRut** [comment]
At least on my instance this can be fixed by manually deinstalling the `dacite` dependency and force installing `dacite==1.8.1`.
@LaggAt Could you maybe try to bump the `dacite` dependency to `1.8.1`?
