### ISSUE TITLE
object has no attribute 'rate_limit_delay'

### ISSUE THREAD

**Issue by ThierryBegin** [LaggAt/hacs-govee#180]
## Version of the custom_component
2023.11.1

## Describe the bug
Govee integration won't connect

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 10:50:33 AM (5 occurrences)
Last logged: 3:12:08 PM

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?

```

**Comment by chaosclarity84** [comment]
Also getting this. Just updated to latest HA.

**Comment by CT-Biggles** [comment]
> Also getting this. Just updated to latest HA. Is anyone even maintaining this any more? Guess I need to drop all my Govee stuff...

You might want to try the govee2mqtt addon. That seems to be working but requires mqtt broker.

**Comment by TobiTenno** [comment]
I had similar impact with the mqtt integration that I do with the rate limiting issue... The mqtt version doesn't seem to publish updates as fast as would be ideal for reactive automations.
