### ISSUE TITLE
API Limit Keeps getting hit

### ISSUE THREAD

**Issue by Dawe5ome** [LaggAt/hacs-govee#190]
## Version of the custom_component

[2023.11.1](https://github.com/LaggAt/hacs-govee/tree/2023.11.1)

## Configuration
I am running HA on a Raspberry Pi 5 using docker (as I have other integrations working on my pi). 

I have **10 lights** that I am controlling, they are:
- **8xH6008** (Govee Smart Light Bulbs, Color Changing Light Bulb, Work with Alexa and Google Assistant, 16 Million Colors RGBWW, WiFi & Bluetooth LED Light Bulbs, Music Sync, A19, 800 Lumens) 
- **1xH605C** (Govee Envisual TV LED Backlight T2)
-  **1xH7021** (Govee Smart Outdoor String Lights H7021, RGBIC Warm White 96ft (2 Ropes of 48ft) LED Bulbs, WiFi Patio Lights Work with Alexa, Google, APP Control, IP65 Waterproof)

My set up of the lights looks like this:
- **Bedroom**: 2xH6008s (both in a helper light group called Bedroom)
- **Kitchen**: 3xH6008s (all in a helper light group called Kitchen)
- **Living Room**: 2xH6008s (both in a helper light group called Living Room), 1xH605C (not in helper light group)
- **Entry Way:** 1xH6008
- **Patio**: 1xH7021

Here are the settings I have with it:
![image](https://github.com/user-attachments/assets/2178784d-adfd-4360-b4e7-2f1acfe3db7b)
![image](https://github.com/user-attachments/assets/623534e8-13b3-45bd-a266-e11cf189dfff)

## Describe the bug
The API limit of 10000 requests every 24 hours keeps being initialized. However this only happens when I assign my lights to an automation. If I leave my lights just as their own then I typically don't have issues besides the odd disconnect. I decided today would be a good day to test out an automation for turning on my lights if my home state changes from 0 to 1 person coming home. Then I hit the API limit. 

What is the point of having Govee on HA if every time I try to do anything somewhat smart with HA it just hits the limit and I can no longer use it. It has less functionality currently than my Google Home and that thing is absolutely brutal. 

## Debug log

```text
2024-11-21 16:30:07.707 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-21 16:30:07.707 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration govee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-21 16:30:09.702 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7ffe9abfb6d0>, '/usr/local/lib/python3.12/site-packages/certifi/cacert.pem', None, None) inside the event loop by custom integration 'govee' at custom_components/govee/__init__.py, line 53: hub = await Govee.create( (offender: /usr/local/lib/python3.12/ssl.py, line 708: context.load_verify_locations(cafile, capath, cadata)), please create a bug report at https://github.com/LaggAt/hacs-govee/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 53, in async_setup_entry
    hub = await Govee.create(

2024-11-21 16:30:10.029 WARNING (MainThread) [custom_components.govee] API is back online.
2024-11-21 16:30:10.030 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2024-11-21 16:30:10.030 WARNING (MainThread) [custom_components.govee] Could not connect to Govee API: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2024-11-21 16:30:10.030 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'. Did you mean: 'rate_limit_reset'?
2024-11-21 16:30:13.281 ERROR (Thread-6) [pychromecast.socket_client] [Bedroom TV(192.168.2.14):8009] Failed to connect to service MDNSServiceInfo(name='Chromecast-51579980351f5acc98270a4eb03d1e61._googlecast._tcp.local.'), retrying in 5.0s

```

**Comment by shunopoli** [comment]
I am having this same issue. Any resolution?

**Comment by jlexster2024** [comment]
I just started using HA and added this to it and got the same thing. How do I know what constitutes an API call? I have all govee light bulbs at this point and want to use them in automation.

**Comment by YewTreeWeb** [comment]
I'm also having the same issue

**Comment by Dawe5ome** [comment]
For those wondering this is still an issue. Even with no automations I still will get the API limit hit.

Something that has helped reduce it a ton with automations is using Google Assistant SDK 'Send text command'. It's completely out

**Comment by jlexster2024** [comment]
I ended up trying https://github.com/Beshelmek/govee_ble_lights and haven't had a single rate limit yet. Been about a week now. I don't have any more govee entities set to trigger automations, but I was getting rate limited even with no automations before I switched.

**Comment by Sebastian-Voigt** [comment]
Same issue here

**Comment by Dawe5ome** [comment]
> I ended up trying https://github.com/Beshelmek/govee_ble_lights and haven't had a single rate limit yet. Been about a week now. I don't have any more govee entities set to trigger automations, but I was getting rate limited even with no automations before I switched.

How did you end up installing this? There isn't an installation guide on it

**Comment by jlexster2024** [comment]
> > I ended up trying https://github.com/Beshelmek/govee_ble_lights and haven't had a single rate limit yet. Been about a week now. I don't have any more govee entities set to trigger automations, but I was getting rate limited even with no automations before I switched.
> 
> How did you end up installing this? There isn't an installation guide on it

Okay, so you have to have HACS. You go into that, click the three dots in the top right and select "Custom repositories" and put in the URL for the github. It'll be available as an integration then.

**Comment by Dawe5ome** [comment]
> > > I ended up trying https://github.com/Beshelmek/govee_ble_lights and haven't had a single rate limit yet. Been about a week now. I don't have any more govee entities set to trigger automations, but I was getting rate limited even with no automations before I switched.
> > 
> > 
> > How did you end up installing this? There isn't an installation guide on it
> 
> Okay, so you have to have HACS. You go into that, click the three dots in the top right and select "Custom repositories" and put in the URL for the github. It'll be available as an integration then.

Do I need to have this?

> For Direct BLE Control:
> Before you begin, make certain HomeAssistant can access BLE on your platform. Ensure your HomeAssistant instance is granted permissions to utilize the Bluetooth Low Energy of your host machine.

Or will I be fine without it. I am running HA on a Pi5 in Docker

**Comment by jlexster2024** [comment]
It should give you an option to use API or BLE when you configure it. Use API like you did with the hacs-govee one.

**Comment by Mastiha101** [comment]
It doesn't work for me. I've added it via the Custom repositories, but it doesn't seem to add anything. It also gets removed if I restart the server, as it doesn't appear in the Custom repositories anymore.

**Comment by gabosom** [comment]
super unfortuante. I keep hitting these rate limits daily and renders the integration unusable.

I was reading the API and there are some mechanisms to limit but I am not well versed on Python enough to fix it myself. @LaggAt , have you run into some of these rate issues yourself? 

![Image](https://github.com/user-attachments/assets/c5aafb3f-6d3f-4ddd-90dd-943373477144)

**Comment by Cobra-James** [comment]
Same issue here... moved from home bridge to this via HACS and it's not really worked for longer than 2 hours, rate limit hit really fast.

**Comment by gargantuanprism** [comment]
the default polling interval of 10 seconds will obviously trigger the API limit (21600 requests in 24h). i changed it to 60 seconds during setup a few days ago and it's been fine. i have 3 govee devices and turn them on/off maybe 10 times per day.

**Comment by DouweM** [comment]
@gargantuanprism I think your math is off -- polling every 10 seconds means 24 * 60 * 6 = 8640 requests per 24 hours, so that should be under the 10k limit. I'm not sure if separate requests are performed for each device -- that would increase the rate significantly, of course.

Either way, I've also been hitting the 10k limit and I'm going to try increasing the polling interval.

**Comment by mavproductions** [comment]
Any updates? I'm using only 1 H6008 and it seems after only a few changes I can't send anymore requests and the logs say I'm being rate limited, even after setting poll rate to 30s 😑

Edit: Trying to decide if I want to refund my 4-pk lol. Any feedback would be great

**Comment by DouweM** [comment]
@mavproductions I ended up switching to https://github.com/Beshelmek/govee_ble_lights, which has been working great (and supports the API despite the name suggesting it's Bluetooth only).

**Comment by mavproductions** [comment]
> [@mavproductions](https://github.com/mavproductions) I ended up switching to https://github.com/Beshelmek/govee_ble_lights, which has been working great (and supports the API despite the name suggesting it's Bluetooth only).

I tried API method and no luck. When I go to BLE, in the drop down H6008 isn't listed.

![Image](https://github.com/user-attachments/assets/3ae2a8cf-8f6f-4207-8a06-0c6aca02c168)

![Image](https://github.com/user-attachments/assets/9df3e44b-0e06-41d8-91f6-e0cc318aff54)
