### ISSUE TITLE
MacOS Govee API Key request goes into error 2.0b

### ISSUE THREAD

**Issue by yepperak** [LaggAt/hacs-govee#31]
## Version of the custom_component
0.2.0b
@LaggAt
45
1
hacs
Project Maintenance
BuyMeCoffee

Component to integrate with Govee.

-->

## Configuration

```yaml

Add your logs here.

Logger: custom_components.govee.config_flow
Source: custom_components/govee/config_flow.py:34 
Integration: Govee (documentation, issues) 
First occurred: 9:24:08 PM (2 occurrences) 
Last logged: 9:32:41 PM

Cannot connect: API: API-Error -1: _api_request_internal: error from aiohttp: ClientConnectorCertificateError(ConnectionKey(host='developer-api.govee.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))
Traceback (most recent call last):
  File "/Users/gary/.homeassistant/custom_components/govee/config_flow.py", line 68, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
  File "/Users/gary/.homeassistant/custom_components/govee/config_flow.py", line 34, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error -1: _api_request_internal: error from aiohttp: ClientConnectorCertificateError(ConnectionKey(host='developer-api.govee.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)'))

## Describe the bug
A clear and concise description of what the bug is.

**Comment by LaggAt** [comment]
That looks like a certificate issue, maybe your time is wrong or a root certificate is missing? Maybe it was a temporary certificate issue on the https server?
