### ISSUE TITLE
Error during configuration - generator didn't stop after athrow

### ISSUE THREAD

**Issue by gmalbert** [LaggAt/hacs-govee#7]
## Version of the custom_component

I can't tell as I wasn't able to set it up through integrations. I got as far as adding it via HACS but when I got to Configuration > Add > Govee and then input the api key, I got an "Unknown error".
## Configuration

```yaml
None. Set up via Integrations per instructions.
Add your logs here.

```

## Describe the bug
I get an "Unknown Error" when I attempt to add my API key in the configuration. I'm using Docker on ubuntu 18.04 with HA .118.5.

## Debug log

```text

Add your logs here.
Logger: custom_components.govee.config_flow
Source: custom_components/govee/config_flow.py:25
Integration: Govee LED strips (documentation, issues)
First occurred: 8:59:21 PM (1 occurrences)
Last logged: 8:59:21 PM

Unexpected exception: generator didn't stop after athrow()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 168, in _api_request_internal
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 151, in _api_get
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 355, in get_devices
    for item in result["data"]["devices"]:
KeyError: 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 45, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/govee/config_flow.py", line 25, in validate_input
    _, error = await hub.get_devices()
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 409, in get_devices
    err = f"API-Error {response.status}: {result}"
  File "/usr/local/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 151, in _api_get
    yield response
  File "/usr/local/lib/python3.8/contextlib.py", line 190, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow()
```

**Comment by LaggAt** [comment]
Hi, are you sure your API Key is correct?

**Comment by gmalbert** [comment]
@LaggAt I copied and pasted it directly from the email sent to me by Govee. I tried it a couple of times as well.

**Comment by danielmhair** [comment]
I got this same thing. I'm going to try a different version

**Comment by danielmhair** [comment]
Same thing happened when I used v0.1.5.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 169, in _api_request_internal
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 152, in _api_get
    yield response
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 356, in get_devices
    for item in result["data"]["devices"]:
KeyError: 'devices'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 44, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/govee/config_flow.py", line 24, in validate_input
    _, error = await hub.get_devices()
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 410, in get_devices
    err = f"API-Error {response.status}: {result}"
  File "/usr/local/lib/python3.8/contextlib.py", line 189, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/govee_api_laggat/govee_api_laggat.py", line 152, in _api_get
    yield response
  File "/usr/local/lib/python3.8/contextlib.py", line 190, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow()
```

**Comment by daren-malfait** [comment]
I'm getting the exact same error. Running in a docker home-assistant docker container on a rapsberry pi 4.

**Comment by koerly** [comment]
I'm getting the exact same "unknown error" with the same Log  as above.
Trying to connect a configured and working Govee Strip H6181

**Comment by casperaudenaert2** [comment]
i am getting this error too

**Comment by jstnkndll** [comment]
I think it's the Govee api key, something that Govee will have to fix possibly

**Comment by LaggAt** [comment]
think the library hides the correct error, which is addressed here:
https://github.com/LaggAt/python-govee-api/tree/bug/%237_eror_during_configuration

I expect that to be an useful information now, maybe some api stuff, so I'll close here.
Please await the release of the integration before reopening :) Thanks.
