### ISSUE TITLE
Govee API has suddenly stopped responding

### ISSUE THREAD

**Issue by Smoothy13** [LaggAt/hacs-govee#73]
## Version of the custom_component
<Version 0.2.2
-->

## Configuration
Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee ([documentation](https://github.com/LaggAt/hacs-govee/blob/master/README.md), [issues](https://github.com/LaggAt/hacs-govee/issues))
First occurred: 3:45:19 PM (1 occurrences)
Last logged: 3:45:19 PM

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

## Describe the bug
The Integration has a red box around it, states "Failed to setup".  It was working for months, then without any updates to anything....I noticed it.  Tried rebooting HA, updating it to 0.2.2.  No luck

![2022-05-05 16_03_59-Settings – Home Assistant and 2 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/105019387/167025297-dfb1b348-1be7-4fe9-b329-e0026229deca.png)
![2022-05-05 16_05_00-Settings – Home Assistant and 2 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/105019387/167025396-a767888e-73ed-4a35-a7ec-65d2ecd8089c.png)
![2022-05-05 16_05_43-Settings – Home Assistant and 2 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/105019387/167025467-1cfeb0f3-540d-41ee-899b-1a06c0afdac9.png)

**Comment by giantsystems** [comment]
Seeing the same issue. Started today.

**Comment by domemshur** [comment]
Same for me

**Comment by mikem30303** [comment]
Another, I have 3 Govee lights and all offline.  Started today too.

**Comment by Scope666** [comment]
Same for me with both of my H6159 strips.

**Comment by wavesswe** [comment]
Same for me, the app works but the integration fails to connect. I even tried with a new API key.

**Comment by ssdhanas12** [comment]
Same here. There is another thread tied to this issue. Please follow over there

**Comment by omayhemo** [comment]
Same.

**Comment by jlips24** [comment]
Also seeing this issue starting today

**Comment by dinan5** [comment]
Same here,

**Comment by Dmellons** [comment]
Same here.

**Comment by jsheph** [comment]
I am also experiencing this issue. Govee announced on April 1st 2022 that there were changes coming to their API service. Not sure if this is the cause but it's somewhat coincidental. Here is a copy of their email regarding the update as well as a copy of the new API documentaiton if interested:

_Thank you for choosing Govee and for your constant support!

For 2022, we have some important updates for our Govee API to inform you about.

1. “Govee API” has been officially renamed to the more standard “Govee Developer API”.


2. We have updated the Terms of Service for the Govee Developer API to better protect the legitimate rights and interests of both parties. 

3. Due to the limited resources of the API server, the flow of some high-frequency API calls will be limited in order to make the API server more stable and serve more users.

If your current usage scenario does not call the API frequently, your applications will not be affected.
If your current usage scenario calls the API frequently, your application might be affected and may not function properly. Therefore, you will need to modify your applications to call the API less frequently. Specific rules related to this are listed in the latest API reference document.
The limit on API call frequency will be implemented started May 5, 2022. We hope you can complete any needed modification of your API applications before this date so your applications will continue to run normally.
If you have any question, please contact us via api-support@govee.com._
[GoveeDeveloperAPIReference.pdf](https://github.com/LaggAt/hacs-govee/files/8637024/GoveeDeveloperAPIReference.pdf)

**Comment by kiragengis** [comment]
You all should have received an email with the subject “Important Updates for Govee API” on April 1st. Here is the link to the documentation of the new api: https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf

now we need that someone updates the integration.

**Comment by a-bianucci** [comment]
Same here. Tried to get a new API key thinking something was happening and I was rate limited, now also getting:

govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited,the limit is max 10000 in 86400000 seconds. see X-RateLimit-Reset in Response Header"}

**Comment by SwannyBFC** [comment]
Also got the same, will be due to the new API, taken from their recent email -

The limit on API call frequency will be implemented started May 5, 2022. We hope you can complete any needed modification of your API applications before this date so your applications will continue to run normally.

**Comment by mondi31** [comment]
same

**Comment by Engel7955** [comment]
Since yesterday and already against

**Comment by Morteum9** [comment]
https://github.com/LaggAt/hacs-govee/issues/72 seems to be impacting most people and have another thread on it currently

**Comment by atv2016** [comment]
same here, rate limited

**Comment by DERFAUSt** [comment]
same issue..... here is an email .i got from govee support.....

Thank you for contacting Govee here.
Due to the limited resources of the API server, the flow of some high-frequency API calls will be limited in order to make the API server more stable and serve more users.
The limit on API call frequency was implemented started May 5, 2022. 
If your current usage scenario calls the API frequently, your application might be affected and may not function properly. 
Therefore, you will need to modify your applications to call the API less frequently. 

Specific rules related to this are listed in the latest API reference document here：
https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf 

Thank you for your understanding.

**Comment by TomCasavant** [comment]
> Is the integration developer still active on this ? Wonder if they can reduce the amount of requests sent to govee

We should really unify this into one issue, but you can adjust how often homeassistant polls Govee yourself which might help https://github.com/LaggAt/hacs-govee/issues/72#issuecomment-1120006418

**Comment by ironicbadger** [comment]
<img width="731" alt="image" src="https://user-images.githubusercontent.com/2773080/167230998-77844311-5497-4ce7-a2d0-6babb618644e.png">

This is why. I should have known better than to buy light which required a cloud connection.

**Comment by omayhemo** [comment]
> This is why. I should have known better than to buy light which required a cloud connection.

Exactly my thoughts.  I'll be creating an alternative.  This just happened to be an easy way to do what I wanted to do.

**Comment by Eric2XU** [comment]
Well reasonable limits on API calls is fine, I think the major issue here is what pooling frequency will keep the APIs happy? 

I have 7 devices... so would my math be right? 60 seconds per min times 60 in an hour gives me 3600 second per hour times 24 hours is 86400 seconds in 24 hours rate limit? 

So 86400 seconds in the day...  If I pool every 65 seconds, thats 86400/65 = 1329 times my 7 devices is about 9.3K API calls within the 24 hours period of time. Close enough to my 10K rate limit.  Going to try that and see. 

I think my largest issue with this is the rate limit should be reflective of number of devices if each device ends up with another api call (not sure if thats the case or not). 

I am ok with cloud services, I just think Govee needs to set a rate limit that still enables us to effectively use the product within homeAssistant.

**Comment by jpc1991** [comment]
Same issue as described above. Wonder if there will be a fix. For now disabling this addon.

**Comment by dinan5** [comment]
I changed my polling value to 300 and it’s been running for a day without issue. You may need to wait for a day to pass to reset api counters on their side I’m guessing.



On May 8, 2022, at 13:50, jpc1991 ***@***.***> wrote:

﻿

Same issue as described above. Wonder if there will be a fix. For now disabling this addon.

**Comment by jpc1991** [comment]
I tried setting the polling interval manually, but now I can't connect at all, and all my entities disappeared.

2022-05-08 13:18:17 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2022-05-08 13:18:17 ERROR (MainThread) [custom_components.govee.config_flow] Cannot connect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 68, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
  File "/config/custom_components/govee/config_flow.py", line 34, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

**Comment by dinan5** [comment]
Wait it out.

On May 8, 2022, at 14:20, jpc1991 ***@***.***> wrote:

﻿

I tried setting the polling interval manually, but now I can't connect at all, and all my entities disappeared.

2022-05-08 13:18:17 WARNING (MainThread) [govee_api_laggat.api] Rate limit exceeded, check if other devices also utilize the govee API
2022-05-08 13:18:17 ERROR (MainThread) [custom_components.govee.config_flow] Cannot connect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
Traceback (most recent call last):
File "/config/custom_components/govee/config_flow.py", line 68, in async_step_user
user_input = await validate_api_key(self.hass, user_input)
File "/config/custom_components/govee/config_flow.py", line 34, in validate_api_key
raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

**Comment by Eric2XU** [comment]
Yeah I can confirm if you find a polling value that keeps you under 10K requests per day then it will within about 24 hours return to service. I would also highly recommend disabling the plugin all together for those 24 hours so no attempts are made to help reset the counter.

**Comment by atv2016** [comment]
yeah can confirm, i disabled for 24h or so and set polling to 100, working fine again for me.

**Comment by enricodx** [comment]
> yeah can confirm, i disabled for 24h or so and set polling to 100, working fine again for me.

Sorry to bother you... could you be so kind to tell me exactly where to set polling to 100 (files and lines)?

Thanks!
