### ISSUE TITLE
All Govee LEDs not avalible

### ISSUE THREAD

**Issue by xxLexanixx** [LaggAt/hacs-govee#90]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee (documentation, issues)
First occurred: 11:38:36 (1 occurrences)
Last logged: 11:38:36

Error setting up entry Govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

**Comment by Minituff** [comment]
You most likely need to increase the Poll Interval. Govee [made changes](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf) to the API on May 5th.


<img width="439" alt="image" src="https://user-images.githubusercontent.com/8152401/184685291-81d98e98-1be9-4841-996f-6d162b53a143.png">

**Comment by endnic** [comment]
The error occurs if it isn't possible to get all devices from the API. And I guess that occurs because your rate limit exceeded. At least that is the problem on my side.
