### ISSUE TITLE
Error setting up entry govee for govee

### ISSUE THREAD

**Issue by almighty059** [LaggAt/hacs-govee#91]
Govee never seems to work. I disconnected all of my Govee products and now I only have two that sit here in hopes of working. I thought they were supposed to come out with local support.?

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee (documentation, issues)
First occurred: August 1, 2022 at 6:05:51 PM (1 occurrences)
Last logged: August 1, 2022 at 6:05:51 PM

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

**Comment by iqtedar123** [comment]
I have the same issue. Hopefully gets fixed.

**Comment by mortyone** [comment]
Same issue as at 3rd Sept 2022, It used to work fine. I've reinstalled from scratch, also applied for a new API key etc, but still no joy.

**Comment by Doom666DE** [comment]
Ich habe genau das gleiche Problem! Habe schon neue APIs probiert, funktioniert paar Stunden und dann plötzlich nicht mehr. Ich habe auch in der Zeit auch keine 60 Befehle die Stunde ausgeführt. Ich hoffe, dass seitens Govee auch mehr Richtung HA kommt und einerseits die APIs zuverlässiger laufen und dass man auch mehr Möglichkeiten bekommt wie z.B. die gespeicherten DIYs auswählen zu können.

**Comment by wolfjank** [comment]
Same Problem here. Anyone working on the Problem?
