### ISSUE TITLE
Home Assistant 2022.10.3 Breaking Change???

### ISSUE THREAD

**Issue by Gahawn** [LaggAt/hacs-govee#94]
After updating to HA 2022.10.3 the Govee integration has stopped working. I've attached an image of the log.

I also tried requesting a new API key. It tells me it cannot connect. 

![Image 002](https://user-images.githubusercontent.com/12971120/195746719-514543d4-ca24-4401-8b4a-b5b31c54d16c.png)

**Comment by deonte1threatt** [comment]
Same here. Attempted to use a new api key and it cannot connect.

**Comment by keler8** [comment]
Same here. :(

**Comment by The-Techy** [comment]
Same

**Comment by GeorgeBark** [comment]
Same 🥲

**Comment by fuzzysb** [comment]
you are rate limited, only 10 messages per minute, so i changed the config for the plugin for 3 devices from 10 to 30 and io no longer get rate limited. but status changes are slower.

**Comment by Gahawn** [comment]
> you are rate limited, only 10 messages per minute, so i changed the config for the plugin for 3 devices from 10 to 30 and io no longer get rate limited. but status changes are slower.

That plus a new API key seems to have resolved the issue for me. Thanks very much. I suspect the HA update was merely coincidental.

**Comment by himanshu-jain16** [comment]
same here

**Comment by idodov** [comment]
Same here.
It stopped work without any update.
Got a new API key, reinstall the integration and now getting error messenge: "Cannot connect. Is the API-Key correct and the internet connection working?".

Log Details (ERROR)
This error originated from a custom integration.
Logger: custom_components.govee.config_flow
Source: custom_components/govee/config_flow.py:34
Integration: Govee (documentation, issues)
First occurred: 1:26:00 AM (5 occurrences)
Last logged: 1:29:58 AM

Cannot connect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
Traceback (most recent call last):
  File "/config/custom_components/govee/config_flow.py", line 128, in async_step_user
    user_input = await validate_api_key(self.hass, user_input)
  File "/config/custom_components/govee/config_flow.py", line 34, in validate_api_key
    raise CannotConnect(error)
custom_components.govee.config_flow.CannotConnect: API: API-Error 429: {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}

**Comment by johnneerdael** [comment]
Like others set, your more then likely being rate limited, check yourself with this command:
curl --location --request GET 'https://developer-api.govee.com/v1/devices' --header 'Govee-API-Key: <API-KEY>'

If you get this, increase your polling frequency massively and try again the next day:
{"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}%
